---
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
title: Predictors of Antidepressant Response and Side Effects in the Genetic Links to Anxiety and Depression (GLAD) Study
subtitle: Analysis Report
author: Yuhao Lin
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  comment = NA,
  prompt = FALSE,
  cache = FALSE,
  asis = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10,
  fig.height = 7,
  fig.fullwidth = TRUE,
  out.width = "180%"
)
options(knitr.kable.NA = "")
options(width = 200)
``` 

```{r clear global environment, include = FALSE} 
remove(list = ls())
```

```{r loading packages, include = FALSE}
setwd("../")
library(ProjectTemplate)
library(tidyverse)
library(ggrepel)
library(kableExtra)
load.project()
```


## Analysis 1

```{r, results = "asis"}
for (m in (only_sig(m1_1))) {
  if (attr(m, "dep") == "mean_n_se") {
    cat(kable_hurd(m))
  } else {
    cat(kable_prop(m))
  }
}
```


## Analysis 2


```{r, results = "asis"}
for (m in (only_sig(m2_1))) {
  cat(kable_prop(m))
}
```



